name: Validate pull request

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:      
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Authenticate using SFDX_AUTH_URL'
        run: echo "hej"
