name: Validate pull request

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:      
      - name: 'Checkout source code'
        run: echo 'lol'
